dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t tp_client .
      - docker images
      - docker tag tp_client $DOCKER_USERNAME/tp_client
      - docker push $DOCKER_USERNAME/tp_client