version: '3.5'
services:
# tp client
  tp-client:
    build:
      context: .
    container_name: tp_client
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - SAWTOOTH_REST_ENDPOINT=http://localhost:8008
      - TP_FAMILY='CattleChain'
      - TP_VERSION='0.0.2'
      - TP_NAMESPACE='ebc4f9'
      - DB_NAME=cattlechain
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SYNC=true
      - DB_DIALECT=postgres
    depends_on:
      - postgres
    networks:
      - default



#postgres
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cattlechain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - default


# network
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
