version: '3.5'
services:
# tp client
  tp-client:
    build:
      context: .
    container_name: tp_client
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - SAWTOOTH_REST_ENDPOINT=http://46.17.108.38:8008
      - TP_FAMILY='CattleChain'
      - TP_VERSION='0.0.2'
      - TP_NAMESPACE='ebc4f9'
      - DB_NAME=cattlechain
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

#postgres
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cattlechain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root